const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('@expo/config-plugins');

/**
 * Keeps react-native-skia compiling under Xcode 26.
 *
 * Skia keeps its C++ headers as a source tree and points at it from its podspec
 * with a quoted recursive search path ("cpp/"/**), which Xcode 26 does not
 * honour, while CocoaPods symlinks the pod's headers FLAT into
 * Pods/Headers/Private/react-native-skia. Its own includes are directory-based
 * ("include/core/SkImage.h", "modules/...", "src/...", "third_party/..."), so
 * they stop resolving and an iOS build dies on missing headers that are sitting
 * right there in node_modules.
 *
 * Fix: re-expose the real trees inside the private headers dir the pod already
 * searches. This has to live in the Podfile rather than in ios/ directly,
 * because ios/ is gitignored and regenerated by prebuild (found the hard way,
 * 2026-08-19: seven failed builds).
 *
 * Remove once skia ships a podspec that works under Xcode 26.
 */
const MARKER = '# niyora: skia header links';

const HOOK = `
    ${MARKER} — see plugins/withSkiaHeaderLinks.js
    priv = File.join(installer.sandbox.root, 'Headers', 'Private', 'react-native-skia')
    cpp = File.expand_path('../../node_modules/@shopify/react-native-skia/cpp', installer.sandbox.root)
    if File.directory?(priv) && File.directory?(cpp)
      {
        'include' => 'skia/include',
        'modules' => 'skia/modules',
        'src' => 'skia/src',
        'third_party' => 'api/third_party',
      }.each do |link, target|
        p = File.join(priv, link)
        File.delete(p) if File.symlink?(p)
        File.symlink(File.join(cpp, target), p) unless File.exist?(p)
      end
    end
`;

const withSkiaHeaderLinks = (config) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const src = fs.readFileSync(podfile, 'utf8');
      if (src.includes(MARKER)) return cfg;
      const anchor = 'post_install do |installer|\n';
      if (!src.includes(anchor)) {
        throw new Error('withSkiaHeaderLinks: no post_install block in the Podfile');
      }
      fs.writeFileSync(podfile, src.replace(anchor, anchor + HOOK), 'utf8');
      return cfg;
    },
  ]);

module.exports = withSkiaHeaderLinks;
